-- ============================================================
-- WIAL Platform — Allow audio/mpeg uploads in chapter-assets bucket
-- Migration: 00015_chapter_assets_audio
-- ============================================================
-- The chapter-assets bucket is used to store background music MP3 files
-- generated by ElevenLabs. The bucket was originally restricted to images
-- and PDFs only; this migration adds audio/mpeg support.
-- ============================================================

UPDATE storage.buckets
SET
  allowed_mime_types = ARRAY[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/avif',
    'application/pdf',
    'audio/mpeg'
  ],
  -- Raise limit to 10 MB to accommodate ~20-second MP3 clips
  file_size_limit = 10485760
WHERE id = 'chapter-assets';
